### ISSUE TITLE
Allow specifying Xmx, Xms, JAVA_OPTS values?

### ISSUE THREAD

**Issue by johanhaleby** [alexanderkiel/datomic-free#13]
Would it be possible for you to add support for passing in Xmx, Xms and JAVA_OPTS when starting a transactor? E.g.

```
bin/transactor $XMX $XMS $JAVA_OPTS /opt/datomic/config/transactor.properties
```

Or is this possible in some other way? If not I could create a PR.

**Comment by alexanderkiel** [comment]
Sorry for the delay. This works already. I added documentation in the README.
